accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.home, name='home'),
    
    #reset_password  
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    
    #change_password
    path('change_password/', views.change_password, name='change_password'),
   ]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:blogpost>/', views.blogpost, name='blogpost'),
    path('like/<slug:blogpost>',views.like, name = 'like'),
    path('comment/<slug:blogpost>',views.add_comment, name = 'add_comment'),



]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('profile/', views.edit_profile, name='edit_profile'),

    path('addresses/', views.addresses, name='addresses'),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),


    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),

    path('stores/', views.stores, name='stores'),
    path('store/<slug:slug>/products', views.store_products, name='store_products'),
    path('store/<slug:slug>/orders', views.store_orders, name='store_orders'),
    path('store/<slug:slug>/orders/<int:order_id>', views.store_order_details, name='store_order_details'),
    path('store/<slug:slug>/orders/<int:order_id>/accept_order', views.accept_order, name='accept_order'),  
    path('store/<slug:slug>/orders/<int:order_id>/order_completed', views.order_completed, name='order_completed'),  
    path('store/<slug:slug>/orders/<int:order_id>/order_canceled', views.order_canceled, name='order_canceled'),  


    #user orders
    path('orders/', views.orders, name='orders'),
    path('orders/order/<int:order_id>', views.order_details, name ='user_order_details'),


   
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('create_store/', views.createStore, name='create_store'),
    path('stores/store/<slug:slug>', views.store, name='store_dashboard'),
    path('stores/store/<slug:slug>/add_product', views.add_product, name='add_product'),
    path('submit_review/<slug:category_slug>/<slug:product_slug>/', views.submit_review, name='submit_review'),
    path('all_stores/', views.all_stores, name='all_stores'),
    path('edit-product/<slug:product_slug>/', views.edit_product, name='edit_product'),
    path("products/delete/<slug:product_slug>/", views.delete_product, name="delete_product"),

    path('all_stores/single_store/<slug:slug>', views.single_store, name='single_store'),
    path('store/edit-store/<slug:slug>/', views.edit_store, name='edit_store'),
    path("stores/delete/<slug:slug>/", views.delete_store, name="delete_store"),
    
]

support/urls.py
from django.urls import path
from . import views

app_name = 'support'

urlpatterns = [
    #tickets
    path('tickets/', views.tickets, name='tickets'),
    path('tickets/single_ticket/<int:ticket_id>', views.single_ticket, name='single_ticket'),
    path('tickets/single_ticket/submit', views.submit_ticket, name='submit_ticket'),

]

tufleur/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('marketplaceadmin/', include('adminshop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('discover.urls', namespace='discover')),
    path('', include('store.urls', namespace='store')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('order.urls', namespace='order')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('notifications.urls', namespace='notifications')),
    path('', include('support.urls', namespace='support')),



    path('ckeditor/', include('ckeditor_uploader.urls')),



]
 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from .models import User, UserProfile, Address
from django.forms import TextInput,FileInput



class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ( 'city',  'country', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [ "address_line1", "address_line2", "city", "country", "zipcode"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["address_line1"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Address line 1"}
        )
        self.fields["address_line2"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Address line 2"}
        )
        self.fields["city"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "City"}
        )
        self.fields["country"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Country"}
        )
        self.fields["zipcode"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Zipcode"}
        )

accounts/views.py
from django.shortcuts import render, reverse

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegistrationForm, UserProfileForm, UserForm, UserAddressForm
from .models import User, UserProfile, Address
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

# Verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            user = User.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.phone_number = phone_number
            user.save() 

            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            profile.profile_picture = '/users/images/user.png'
            profile.save()
            
            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            messages.success(request, 'Thank you for registering with us. We have sent you a verification email to your email address. Please verify it.')
            return redirect('/accounts/login/?command=verification&email='+email)  
    else:
        form = RegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)



def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('discover:home')
        else:
            messages.error(request, 'Invalid login credentials')
            return redirect('accounts:login')
    return render(request, 'accounts/login.html')


@login_required(login_url = 'login')
def logout(request):
    auth.logout(request)
    messages.success(request, 'You are logged out.')
    return redirect('discover:home')

def home(request):
    return render(request, 'home.html')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your account is activated.')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Invalid activation link')
        return redirect('accounts:register')




def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__exact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = 'Reset Your Password'
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Account does not exist!')
            return redirect('accounts:forgotPassword')
    return render(request, 'accounts/forgotPassword.html')


def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password')
        return redirect('accounts:resetPassword')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('accounts:login')


def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = User.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Password do not match!')
            return redirect('accounts:resetPassword')
    else:
        return render(request, 'accounts/resetPassword.html')



@login_required(login_url='accounts:login')
def change_password(request):
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        user = User.objects.get(username__exact=request.user.username)

        if new_password == confirm_password:
            success = user.check_password(current_password)
            if success:
                user.set_password(new_password)
                user.save()
                # auth.logout(request)
                messages.success(request, 'Password updated successfully.')
                return redirect('accounts:change_password')
            else:
                messages.error(request, 'Please enter valid current password')
                return redirect('accounts:change_password')
        else:
            messages.error(request, 'Password does not match!')
            return redirect('accounts:change_password')
    return render(request, 'accounts/change_password.html')

accounts/templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on below link to confirm your registration.
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}

<!-- Page Title-->
 <div class="page-title-overlap bg-dark pt-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
      <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
            <li class="breadcrumb-item"><a class="text-nowrap" href="{% url 'discover:home' %}"><i class="ci-home"></i>Home</a></li>
            <li class="breadcrumb-item text-nowrap"><a href="#">Account</a>
            </li>
            <li class="breadcrumb-item text-nowrap active" aria-current="page">Profile info</li>
          </ol>
        </nav>
      </div>
      <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
        <h1 class="h3 text-light mb-0">Profile info</h1>
      </div>
    </div>
  </div>
  <div class="container pb-5 mb-2 mb-md-4">
    <div class="row">
      <!-- Sidebar-->
      <aside class="col-lg-4 pt-4 pt-lg-0 pe-xl-5">
        <div class="bg-white rounded-3 shadow-lg pt-1 mb-5 mb-lg-0">
          <div class="d-md-flex justify-content-between align-items-center text-center text-md-start p-4">
            <div class="d-md-flex align-items-center">
              <div class="img-thumbnail rounded-circle position-relative flex-shrink-0 mx-auto mb-2 mx-md-0 mb-md-0" style="width: 6.375rem;"><img class="rounded-circle" src="{{request.user.userprofile.profile_picture.url}}" alt="user picture"></div>
              <div class="ps-md-3">
                <h3 class="fs-base mb-0">{{user.username}}</h3><span class="text-accent fs-sm">{{user.email}}</span>
              </div>
            </div><a class="btn btn-primary d-lg-none mb-2 mt-3 mt-md-0" href="#account-menu" data-bs-toggle="collapse" aria-expanded="false"><i class="ci-menu me-2"></i>Account menu</a>
          </div>
          <div class="d-lg-block collapse" id="account-menu">
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Account settings</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:edit_profile' %}"><i class="ci-user opacity-60 me-2"></i>Profile info</a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:addresses' %}"><i class="ci-location opacity-60 me-2"></i>Addresses</a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 active" href="{% url 'accounts:change_password' %}"><i class="ci-card opacity-60 me-2"></i>Change password</a></li>
              <li class="d-lg-none border-top mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:logout' %}"><i class="ci-sign-out opacity-60 me-2"></i>Sign out</a></li>
            </ul>
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Dashboard</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:stores' %}"><i class="ci-bag opacity-60 me-2"></i>Stores<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:orders' %}"><i class="ci-bag opacity-60 me-2"></i>Orders<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:wishlist' %}"><i class="ci-heart opacity-60 me-2"></i>Wishlist<span class="fs-sm text-muted ms-auto">3</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'support:tickets' %}"><i class="ci-help opacity-60 me-2"></i>My tickets<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'store:create_store' %}"><i class="ci-help opacity-60 me-2"></i>become vendor </a></li>
            </ul>
          </div>
        </div>
      </aside>
      <!-- Content  -->
      <section class="col-lg-8">
        <!-- Toolbar-->
        <div class="d-none d-lg-flex justify-content-between align-items-center pt-lg-3 pb-4 pb-lg-5 mb-lg-3">
          <h6 class="fs-base text-light mb-0">Change Your Passwor</h6><a class="btn btn-primary btn-sm" href="{% url 'accounts:logout' %}"><i class="ci-sign-out me-2"></i>Sign out</a>
        </div>
        
        <div class="container">
            <div class="row">
            
            <main class="col-md-12">
                <article class="card">
                
                <div class="card-body">
                    <div class="row">
                    <div class="col-md-12">
                        <form action="{% url 'accounts:change_password' %}" method="POST">
                            {% csrf_token %}

                            <div class="form-group">
                                <label>Current Password</label>
                                <input type="password" name="current_password" placeholder="Current Password" class="form-control" required>
                            </div>
                            <br>
                            <div class="form-group">
                                <label>Create new password</label>
                                <input type="password" name="new_password" placeholder="Create New Password" class="form-control" required>
                            </div>
                            <br>
                            <div class="form-group">
                                <label>Confirm new password</label>
                                <input type="password" name="confirm_password" placeholder="Confirm New Password" class="form-control" required>
                            </div>
                            <br>
                            <input type="submit" value="Submit" class="btn btn-primary">
                        </form>
                    </div>

                    </div> <!-- row.// -->
                    </div> <!-- card-body .// -->

                    </article> <!-- order-group.// -->
                </main>
                </div> <!-- row.// -->
                </div>

      </section>
    </div>
  </div>

  {% endblock %}

accounts/templates/accounts/forgotPassword.html
{% extends 'base.html' %}


{% block content %}

<div class="card mx-auto" style="max-width: 1000px; margin-top:100px;">
    <div class="card-body">

  <div class="row justify-content-center">
    {% include 'includes/alerts.html' %}
    <div class="col-lg-8 col-md-10">
      <h2 class="h3 mb-4">Password reset</h2>
      <p class="fs-md">Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
      
      <form action="{% url 'accounts:forgotPassword' %}" method="POST">
        {% csrf_token %}
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->

          <br>
          <div class="form-group Center" >
              <button type="submit" class="btn btn-primary btn-block"  > Submit  </button>
          </div> <!-- form-group// -->
      </form>
    </div>
    <p class="text-center mt-4" >Got yout password? <a href="{% url 'accounts:login' %}"> Login</a></p>
    <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
     <br><br>
  </div>
  </div>

</div>
<br><br>



{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}
{% block content%}  

{% if request.GET.command == 'verification' %}

<div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
Thank you for registering with us. We have sent you a verification email to your email address [{{ request.GET.email }}]
<br><br>
Already verified? <a href="{% url 'accounts:login' %}">Login</a>
</div>

{% else %}
<div class="container py-4 py-lg-5 my-4">
  {% include 'includes/alerts.html' %}

  <div class="row">
    <div class="col-md-6 pt-4 mt-3 mt-md-0">
        <img src="/static/img/login.jpg" alt="" class="img-fluid mb-3 d-none d-md-block">
    </div>

    <div class="col-md-6">
      <div class="card border-0 shadow">
        <div class="card-body">
          <h2 class="h4 mb-1">Login</h2>
          <div class="py-3">
            <h3 class="d-inline-block align-middle fs-base fw-medium mb-2 me-2">With social account:</h3>
            <div class="d-inline-block align-middle"><a class="btn-social bs-google me-2 mb-2" href="#" data-bs-toggle="tooltip" title="Sign in with Google"><i class="ci-google"></i></a><a class="btn-social bs-facebook me-2 mb-2" href="#" data-bs-toggle="tooltip" title="Sign in with Facebook"><i class="ci-facebook"></i></a><a class="btn-social bs-twitter me-2 mb-2" href="#" data-bs-toggle="tooltip" title="Sign in with Twitter"><i class="ci-twitter"></i></a></div>
          </div>
          <hr>
          <h3 class="fs-base pt-4 pb-2">Or using form below</h3>
          
          <form method="POST" action="{% url 'accounts:login' %}">
            {% csrf_token %}  

            <div class="input-group mb-3"><i class="ci-user position-absolute top-50 translate-middle-y text-muted fs-base ms-3"></i>
              <input class="form-control rounded-start" type="email" name="email" placeholder="Email" class="form-control"required>
            </div>

            <div class="input-group mb-3"><i class="ci-locked position-absolute top-50 translate-middle-y text-muted fs-base ms-3"></i>
              <div class="password-toggle w-100">
                <input class="form-control" type="password" name="password" placeholder="Password" required>
                <label class="password-toggle-btn" aria-label="Show/hide password">
                  <input class="password-toggle-check" type="checkbox"><span class="password-toggle-indicator" ></span>
                </label>
              </div>
            </div>

            <div class="d-flex flex-wrap justify-content-between">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" checked id="remember_me">
                <label class="form-check-label" for="remember_me">Remember me</label>
              </div><a class="nav-link-inline fs-sm" href="{% url 'accounts:forgotPassword' %}">Forgot password?</a>
            </div>
            <hr class="mt-4">
            <div class="text-end pt-4">
             <p class="fs-sm text-muted mb-4 d-flex justify-content-md-start" >You don't have an account ?    <a href="{% url 'accounts:register' %}"> Register here </a></p>
              <button class="btn btn-primary" type="submit" value="Login"><i class="ci-sign-in me-2 ms-n21"></i>Login</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
  </div>
</div>
{% endif %}

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content%}

<div class="container py-4 py-lg-5 my-4">
  {% include 'includes/alerts.html' %}

  <div class="row">
    <div class="col-md-6 pt-4 mt-3 mt-md-0">

      <h2 class="h4 mb-3">Register here </h2>
      <p class="fs-sm text-muted mb-4">Registration takes less than a minute but gives you full control over your orders.</p>
      
      <form  method="POST" action="{% url 'accounts:register' %}" class="needs-validation" novalidate>
        
        {% csrf_token %}

        <div class="row gx-4 gy-3">
            <div class="form-row">
            <div class="col form-group">
                <label>First name</label>
                  {{ form.first_name }}
            </div> <!-- form-group end.// -->
            </div>
            <div class="form-row">
            <div class="col form-group">
                <label>Last name</label>
                  {{ form.last_name }}
            </div> <!-- form-group end.// -->
            </div>
            <div class="form-row">
            <div class="form-group ">
                <label>Email Address</label>
                {{form.email}}
              </div> <!-- form-group end.// -->
            </div>
              <div class="form-group ">
                <label>Phone Number</label>
                {{form.phone_number}}
              </div> <!-- form-group end.// -->
              <div class="form-group col-md-6">
                <label>Create password</label>
                {{ form.password }}
            </div> <!-- form-group end.// -->
            <div class="form-group col-md-6">
                <label>Repeat password</label>
                {{form.confirm_password}}
            </div> <!-- form-group end.// -->

          <div class="col-12 text-end">
            <button class="btn btn-primary" type="submit" value="Create User" ><i class="ci-user me-2 ms-n1"></i>Register</button>
          </div>
        </div>
        {{ form.email.errors }}
        {{ form.non_field_errors }}
      </form>
    </div>

    <div class="col-md-6 pt-4 mt-3 mt-md-0">
        <img src="/static/img/login.jpg"  alt="" class="img-fluid mb-3 d-none d-md-block">
        <p class="fs-sm text-muted mb-4 d-flex justify-content-center" >Create an account and enjoy managing your orders !</p>     

      </div>
  </div>
</div>


<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
  </div>
</div>

{%endblock%}

accounts/templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

As requested, please click below link to reset your password.
http://{{domain}}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}