accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.home, name='home'),
    
    #reset_password  
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    
    #change_password
    path('change_password/', views.change_password, name='change_password'),
   ]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:blogpost>/', views.blogpost, name='blogpost'),
    path('like/<slug:blogpost>',views.like, name = 'like'),
    path('comment/<slug:blogpost>',views.add_comment, name = 'add_comment'),



]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('profile/', views.edit_profile, name='edit_profile'),

    path('addresses/', views.addresses, name='addresses'),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),


    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),

    path('stores/', views.stores, name='stores'),
    path('store/<slug:slug>/products', views.store_products, name='store_products'),
    path('store/<slug:slug>/orders', views.store_orders, name='store_orders'),
    path('store/<slug:slug>/orders/<int:order_id>', views.store_order_details, name='store_order_details'),
    path('store/<slug:slug>/orders/<int:order_id>/accept_order', views.accept_order, name='accept_order'),  
    path('store/<slug:slug>/orders/<int:order_id>/order_completed', views.order_completed, name='order_completed'),  
    path('store/<slug:slug>/orders/<int:order_id>/order_canceled', views.order_canceled, name='order_canceled'),  


    #user orders
    path('orders/', views.orders, name='orders'),
    path('orders/order/<int:order_id>', views.order_details, name ='user_order_details'),


   
]

notifications/urls.py
from notifications import views
from django.urls import path

from .views import notifications

app_name = 'notifications'

urlpatterns = [
    path('notifications', views.notifications, name='notifications'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('create_store/', views.createStore, name='create_store'),
    path('stores/store/<slug:slug>', views.store, name='store_dashboard'),
    path('stores/store/<slug:slug>/add_product', views.add_product, name='add_product'),
    path('submit_review/<slug:category_slug>/<slug:product_slug>/', views.submit_review, name='submit_review'),
    path('all_stores/', views.all_stores, name='all_stores'),
    path('edit-product/<slug:product_slug>/', views.edit_product, name='edit_product'),
    path("products/delete/<slug:product_slug>/", views.delete_product, name="delete_product"),

    path('all_stores/single_store/<slug:slug>', views.single_store, name='single_store'),
    path('store/edit-store/<slug:slug>/', views.edit_store, name='edit_store'),
    path("stores/delete/<slug:slug>/", views.delete_store, name="delete_store"),
    
]

support/urls.py
from django.urls import path
from . import views

app_name = 'support'

urlpatterns = [
    #tickets
    path('tickets/', views.tickets, name='tickets'),
    path('tickets/single_ticket/<int:ticket_id>', views.single_ticket, name='single_ticket'),
    path('tickets/single_ticket/submit', views.submit_ticket, name='submit_ticket'),

]

tufleur/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('marketplaceadmin/', include('adminshop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('discover.urls', namespace='discover')),
    path('', include('store.urls', namespace='store')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('order.urls', namespace='order')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('notifications.urls', namespace='notifications')),
    path('', include('support.urls', namespace='support')),



    path('ckeditor/', include('ckeditor_uploader.urls')),



]
 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/models.py
from accounts.models import User
from django.db import models

class Notification(models.Model):
    STORE = 'store'
    ORDER = 'order'
    TICKET = 'ticket'

    CHOICES = (
        (STORE, 'store'),
        (ORDER, 'order'),
        (TICKET, 'ticket'),

    )

    to_user = models.ForeignKey(User, related_name='notifications', on_delete=models.CASCADE)
    notification_type = models.CharField(max_length=20, choices=CHOICES)
    is_read = models.BooleanField(default=False)
    extra_id = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='creatednotifications', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']

notifications/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Notification


@login_required
def notifications(request):
    goto = request.GET.get('goto', '')
    notification_id = request.GET.get('notification', 0)
    extra_id = request.GET.get('extra_id', 0)

    if goto != '':
        notification = Notification.objects.get(pk=notification_id)
        notification.is_read = True
        notification.save()
        if notification.notification_type == Notification.STORE:
            return redirect('dashboard:user_stores')
        elif notification.notification_type == Notification.ORDER:
            return redirect('dashboard:user_orders')
        elif notification.notification_type == Notification.TICKET:
            return redirect('support:tickets')

    return render(request, 'notifications.html')

notifications/templates/notifications.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}

<!-- Page Title-->
 <div class="page-title-overlap bg-dark pt-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
      <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
            <li class="breadcrumb-item"><a class="text-nowrap" href="{% url 'discover:home' %}"><i class="ci-home"></i>Home</a></li>
            <li class="breadcrumb-item text-nowrap"><a href="#">Account</a>
            </li>
            <li class="breadcrumb-item text-nowrap active" aria-current="page">Profile info</li>
          </ol>
        </nav>
      </div>
      <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
        <h1 class="h3 text-light mb-0">Profile info</h1>
      </div>
    </div>
  </div>
  <div class="container pb-5 mb-2 mb-md-4">
    <div class="row">
      <!-- Sidebar-->
      <aside class="col-lg-4 pt-4 pt-lg-0 pe-xl-5">
        <div class="bg-white rounded-3 shadow-lg pt-1 mb-5 mb-lg-0">
          <div class="d-md-flex justify-content-between align-items-center text-center text-md-start p-4">
            <div class="d-md-flex align-items-center">
              <div class="img-thumbnail rounded-circle position-relative flex-shrink-0 mx-auto mb-2 mx-md-0 mb-md-0" style="width: 6.375rem;"><img class="rounded-circle" src="{{request.user.userprofile.profile_picture.url}}" alt="user picture"></div>
              <div class="ps-md-3">
                <h3 class="fs-base mb-0">{{user.username}}</h3><span class="text-accent fs-sm">{{user.email}}</span>
              </div>
            </div><a class="btn btn-primary d-lg-none mb-2 mt-3 mt-md-0" href="#account-menu" data-bs-toggle="collapse" aria-expanded="false"><i class="ci-menu me-2"></i>Account menu</a>
          </div>
          <div class="d-lg-block collapse" id="account-menu">
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Account settings</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 active" href="{% url 'dashboard:edit_profile' %}"><i class="ci-user opacity-60 me-2"></i>Profile info</a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:addresses' %}"><i class="ci-location opacity-60 me-2"></i>Addresses</a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:change_password' %}"><i class="ci-card opacity-60 me-2"></i>Change password</a></li>
              <li class="d-lg-none border-top mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:logout' %}"><i class="ci-sign-out opacity-60 me-2"></i>Sign out</a></li>
            </ul>
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Dashboard</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:stores' %}"><i class="ci-bag opacity-60 me-2"></i>Stores<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:orders' %}"><i class="ci-bag opacity-60 me-2"></i>Orders<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:wishlist' %}"><i class="ci-heart opacity-60 me-2"></i>Wishlist<span class="fs-sm text-muted ms-auto">3</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'support:tickets' %}"><i class="ci-help opacity-60 me-2"></i>My tickets<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'store:create_store' %}"><i class="ci-help opacity-60 me-2"></i>become vendor </a></li>
            </ul>
          </div>
        </div>
      </aside>
      <!-- Content  -->
      <section class="col-lg-8">
        <!-- Toolbar-->
        <div class="d-none d-lg-flex justify-content-between align-items-center pt-lg-3 pb-4 pb-lg-5 mb-lg-3">
          <h6 class="fs-base text-light mb-0">Update you profile details below:</h6><a class="btn btn-primary btn-sm" href="{% url 'accounts:logout' %}"><i class="ci-sign-out me-2"></i>Sign out</a>
          
        </div>
        <!-- Profile form-->
        <div class="bg-secondary rounded-3 p-4 mb-4">
            <h3 class="title">Notifications</h3>
    
            {% if not notifications %}
                No New notifications yet!
            {% endif %}
    
            {% for notification in notifications %}
                <div class="notification">
                    <p>
                        {% if notification.notification_type == 'store' %}
                            <a href="{% url 'notifications:notifications' %}?goto=dashboard:user_stores&notification={{ notification.id }}&extra_id={{ notification.extra_id }}">
                                <strong>From {{ notification.created_by.username }}</strong> : store opening request<br>
                                <small>{{ notification.created_at|timesince }} ago</small>
                            </a>
                        {% elif notification.notification_type == 'order' %}
                            <a href="{% url 'notifications:notifications' %}?goto=dashboard:user_orders&notification={{ notification.id }}&extra_id={{ notification.extra_id }}">
                                <strong>From {{ notification.created_by.username }}</strong> : new order has been placed <br>
                                <small>{{ notification.created_at|timesince }} ago</small>
                            </a>
                        {% else %}
                            <a href="{% url 'notifications:notifications' %}?goto=support:tickets&notification={{ notification.id }}&extra_id={{ notification.extra_id }}">
                                <strong>From Support {{ notification.created_by.username }}</strong> : Your ticket has been updated <br>
                                <small>{{ notification.created_at|timesince }} ago</small>
                            </a>
                        {% endif %}
                    </p>
                </div>
            {% endfor %}
    
            {{notification}}
            
        </div>
       
      </section>
    </div>
  </div>

  {% endblock %}