accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.home, name='home'),
    
    #reset_password  
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    
    #change_password
    path('change_password/', views.change_password, name='change_password'),
   ]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:blogpost>/', views.blogpost, name='blogpost'),
    path('like/<slug:blogpost>',views.like, name = 'like'),
    path('comment/<slug:blogpost>',views.add_comment, name = 'add_comment'),



]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('profile/', views.edit_profile, name='edit_profile'),

    path('addresses/', views.addresses, name='addresses'),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),


    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),

    path('stores/', views.stores, name='stores'),
    path('store/<slug:slug>/products', views.store_products, name='store_products'),
    path('store/<slug:slug>/orders', views.store_orders, name='store_orders'),
    path('store/<slug:slug>/orders/<int:order_id>', views.store_order_details, name='store_order_details'),
    path('store/<slug:slug>/orders/<int:order_id>/accept_order', views.accept_order, name='accept_order'),  
    path('store/<slug:slug>/orders/<int:order_id>/order_completed', views.order_completed, name='order_completed'),  
    path('store/<slug:slug>/orders/<int:order_id>/order_canceled', views.order_canceled, name='order_canceled'),  


    #user orders
    path('orders/', views.orders, name='orders'),
    path('orders/order/<int:order_id>', views.order_details, name ='user_order_details'),


   
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('create_store/', views.createStore, name='create_store'),
    path('stores/store/<slug:slug>', views.store, name='store_dashboard'),
    path('stores/store/<slug:slug>/add_product', views.add_product, name='add_product'),
    path('submit_review/<slug:category_slug>/<slug:product_slug>/', views.submit_review, name='submit_review'),
    path('all_stores/', views.all_stores, name='all_stores'),
    path('edit-product/<slug:product_slug>/', views.edit_product, name='edit_product'),
    path("products/delete/<slug:product_slug>/", views.delete_product, name="delete_product"),

    path('all_stores/single_store/<slug:slug>', views.single_store, name='single_store'),
    path('store/edit-store/<slug:slug>/', views.edit_store, name='edit_store'),
    path("stores/delete/<slug:slug>/", views.delete_store, name="delete_store"),
    
]

tufleur/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('marketplaceadmin/', include('adminshop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('discover.urls', namespace='discover')),
    path('', include('store.urls', namespace='store')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('order.urls', namespace='order')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('notifications.urls', namespace='notifications')),
    path('', include('support.urls', namespace='support')),



    path('ckeditor/', include('ckeditor_uploader.urls')),



]
 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/forms.py
from django.forms import ModelForm, widgets
from django import forms
from .models import Store, Product, ReviewRating


class CreateStoreForm(ModelForm):
    class Meta:
        model = Store
        fields = ['name','logo','description','trader_license', 'phone_number', 'city', 'address']
        def __init__(self, *args, **kwargs):
            super(CreateStoreForm, self).__init__(*args, **kwargs)
            self.fields['trader_license'].required = False

        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product name here..."
            }), 
            "logo": forms.ClearableFileInput(attrs={
                "class": "form-control",
            }),
             "description": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Description of the product...",
                "rows": 5
            }),
            "trader_license": forms.ClearableFileInput(attrs={
                "class": "form-control",
            }),
            "phone_number": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the store's phone number here..."
            }),
            "city": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the store's city location here..."
            }),
            "address": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the store address here..."
            }),

        }


class ProductForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
        "class": "form-control",
        "multiple": True,
    }))

    class Meta:
        model = Product
        fields = ["name","category", "image", "price","description", 'stock', "return_policy",]
        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product name here..."
            }),
            "category": forms.Select(attrs={
                "class": "form-control"
            }),
            "image": forms.ClearableFileInput(attrs={
                "class": "form-control",
            }),
            "price": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Entre price of the product..."
            }),
            "description": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Description of the product...",
                "rows": 5
            }),
			"stock": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Enter product stock ..."
            }),
            "return_policy": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product return policy here..."
            }),
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

store/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, reverse
from store.forms import CreateStoreForm, ProductForm, ReviewForm
from store.models import Store, Product, ProductImage, ReviewRating
from django.shortcuts import render
from django.utils.text import slugify
from django.contrib.auth.models import Group
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.



# Open a Store
@login_required(login_url='accounts:login')

def createStore(request):
    store=Store.objects.filter(owner=request.user)
    user = request.user
    form = CreateStoreForm()
    if request.method == 'POST':
        form = CreateStoreForm(request.POST, request.FILES)
        if form.is_valid():
            store = form.save(commit=False)
            store.owner= user
            store.slug = slugify(store.name)
            store.save()
            form.save()
            store = form.cleaned_data.get('name')

            return redirect('dashboard:stores')

    context = {'form':form, 'store':store}
    return render(request, 'create_store.html', context)


@login_required(login_url='accounts:login')
def edit_store(request, slug):
    store = Store.objects.get(owner=request.user, slug=slug)
    if request.method == 'POST':
        form = CreateStoreForm(request.POST, request.FILES, instance=store)
        
        if form.is_valid():
            form.save()

            return redirect('dashboard:stores', store.slug)
    else:
        form = CreateStoreForm(instance=store)
    
    return render(request, 'edit_store.html', {'form': form, 'store': store})

@login_required(login_url='accounts:login')
def delete_store(request,slug):
    store = Store.objects.get(owner=request.user, slug=slug).delete()
    return redirect("dashboard:stores")


#get specific store
@login_required(login_url='accounts:login')

def store(request, slug):
    store = Store.objects.get(owner=request.user, slug=slug)
    context = {
        'store' : store
    }
    return render(request, 'store_dashboard.html', context)





@login_required(login_url='accounts:login')

def add_product(request, slug):
    store = get_object_or_404(Store, slug=slug)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.added_by = request.user
            product.store = store
            product.slug = slugify(product.name)
            product.save()
            images = request.FILES.getlist("more_images")
            for i in images:
                ProductImage.objects.create(product=product, image=i)

            return redirect('dashboard:store_products', store.slug)
    else:
        form = ProductForm()
    
    return render(request, 'add_product.html', {'form': form,  'store':store})



@login_required(login_url='accounts:login')
def edit_product(request, product_slug):
    store = Store.objects.get(owner=request.user)
    product = Product.objects.filter(store=store, slug=product_slug).first()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        
        if form.is_valid():
            form.save()

            return redirect('dashboard:store_products', store.slug)
    else:
        form = ProductForm(instance=product)
    
    return render(request, 'edit_product.html', {'form': form, 'product': product , 'store':store})

@login_required(login_url='accounts:login')
def delete_product(request,product_slug):
    store = Store.objects.get(owner=request.user)
    product = Product.objects.filter(store=store, slug=product_slug).delete()
    return redirect("dashboard:store_products", store.slug)



@login_required(login_url='accounts:login')
def submit_review(request,  category_slug, product_slug):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product, category__slug=category_slug, slug=product_slug)

    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product.id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.product_id = product.id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)




def all_stores(request):
    stores = Store.objects.all()

    return render(request, 'all_stores.html', {'stores': stores})

def single_store(request, slug):
    single_store = get_object_or_404(Store, slug=slug)
    sproducts = Product.objects.filter(store=single_store)
    return render(request, 'single_store.html', {'single_store': single_store, 'sproducts':sproducts})

store/templates/all_stores.html
 
{% extends 'base.html' %}

{% block title %}All stores | {% endblock %}

{% block content %}
<!-- Item-->
{% if stores %}
<!-- Page Title (Light)-->
<div class="bg-secondary py-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
      <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb flex-lg-nowrap justify-content-center justify-content-lg-start">
            <li class="breadcrumb-item"><a class="text-nowrap" href="index.html"><i class="ci-home"></i>Home</a></li>
            <li class="breadcrumb-item text-nowrap"><a href="#">Stores</a>
            </li>
            <li class="breadcrumb-item text-nowrap active" aria-current="page">All</li>
          </ol>
        </nav>
      </div>
      <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
        <h1 class="h3 mb-0">Marketplace stores</h1>
      </div>
    </div>
  </div>
  <div class="container pb-4 pb-sm-5">
    <!-- stores grid-->
    <div class="row pt-5">
      <!-- Store-->
      {% for store in stores %}
      <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6 px-2 mb-3">
        <div class="card product-card card-static pb-3">
          <a class="card-img-top d-block overflow-hidden" href="{% url 'store:single_store' store.slug %}"><img src="{{store.logo.url}}" alt="Product" width="250"></a>
          <div class="card-body py-2"><a class="product-meta d-block fs-xs pb-1">By {{store.owner.first_name}} {{store.owner.last_name}}</a>
            <h3 class="product-title fs-sm text-truncate"><a href="{% url 'store:single_store' store.slug %}">{{store.name}}</a></h3>
          </div>
          
        </div>
      </div>
      {%endfor%}
      </div>
    </div>
  </div>
  {%else%}
<h3> no store yet ! </h3>


{%endif%}

{% endblock %}

store/templates/create_store.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}

<!-- Page Title-->
 <div class="page-title-overlap bg-dark pt-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
      <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
            <li class="breadcrumb-item"><a class="text-nowrap" href="{% url 'discover:home' %}"><i class="ci-home"></i>Home</a></li>
            <li class="breadcrumb-item text-nowrap"><a href="#">Account</a>
            </li>
            <li class="breadcrumb-item text-nowrap active" aria-current="page">create store</li>
          </ol>
        </nav>
      </div>
      <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
        <h1 class="h3 text-light mb-0">Profile </h1>
      </div>
    </div>
  </div>
  <div class="container pb-5 mb-2 mb-md-4">
    <div class="row">
      <!-- Sidebar-->
      <aside class="col-lg-4 pt-4 pt-lg-0 pe-xl-5">
        <div class="bg-white rounded-3 shadow-lg pt-1 mb-5 mb-lg-0">
          <div class="d-md-flex justify-content-between align-items-center text-center text-md-start p-4">
            <div class="d-md-flex align-items-center">
              <div class="img-thumbnail rounded-circle position-relative flex-shrink-0 mx-auto mb-2 mx-md-0 mb-md-0" style="width: 6.375rem;"><img class="rounded-circle" src="{{request.user.userprofile.profile_picture.url}}" alt="user picture"></div>
              <div class="ps-md-3">
                <h3 class="fs-base mb-0">{{user.username}}</h3><span class="text-accent fs-sm">{{user.email}}</span>
              </div>
            </div><a class="btn btn-primary d-lg-none mb-2 mt-3 mt-md-0" href="#account-menu" data-bs-toggle="collapse" aria-expanded="false"><i class="ci-menu me-2"></i>Account menu</a>
          </div>
          <div class="d-lg-block collapse" id="account-menu">
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Account settings</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 " href="{% url 'dashboard:edit_profile' %}"><i class="ci-user opacity-60 me-2"></i>Profile info</a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="#"><i class="ci-location opacity-60 me-2"></i>Addresses</a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="#"><i class="ci-card opacity-60 me-2"></i>Payment methods</a></li>
              <li class="d-lg-none border-top mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:logout' %}"><i class="ci-sign-out opacity-60 me-2"></i>Sign out</a></li>
            </ul>
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Dashboard</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:stores' %}"><i class="ci-bag opacity-60 me-2"></i>Stores<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:orders' %}"><i class="ci-bag opacity-60 me-2"></i>Orders<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:wishlist' %}"><i class="ci-heart opacity-60 me-2"></i>Wishlist<span class="fs-sm text-muted ms-auto">3</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="#"><i class="ci-help opacity-60 me-2"></i>My tickets<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 active" href="{% url 'store:create_store' %}"><i class="ci-help opacity-60 me-2"></i>become vendor </a></li>
            </ul>
          </div>
        </div>
      </aside>
      <!-- Content  -->
      <section class="col-lg-8">
        <div class="bg-white rounded-3 shadow-lg pt-1 pb-2 mb-5 mb-lg-0">
        <div class="container mt-4 mb-4">
            <div class="col-md-12 ">
                <h2 class="h4 mb-3">Open Store </h2>
                <p class="fs-sm text-muted mb-4">Store creation takes less than a minute but gives you full control over your orders.</p>
                <form  method="POST" action="" enctype='multipart/form-data'>
                  {% csrf_token %}
                  {{form|crispy}}
                  <br>
                <button class="btn btn-primary" value="submit"><i class="ci-store me-2 ms-n21"></i>Create</button>
                </form>
                {% if store %}
                    <hr class="mt-4">
                    <div class="text-end pt-4">
                    <p class="fs-sm text-muted mb-4 d-flex justify-content-md-start" >Already opened {{store|length}} store(s)</p>
                    <a href="{% url 'dashboard:stores' %}"><button class="btn btn-primary"><i class="ci-store me-2 ms-n21"></i>go to my store(s)</button></a>
                    </div>
                {% endif%}
                </div>
            </div>
        </div>
    </div>
      </section>
    </div>
  </div>

  {% endblock %}

store/templates/edit_store.html
{% extends 'base.html' %}

{% load static %}
{% block content%}

 <!-- Dashboard header-->
 <div class="page-title-overlap bg-accent pt-4">
    <div class="container d-flex flex-wrap flex-sm-nowrap justify-content-center justify-content-sm-between align-items-center pt-2">
      <div class="d-flex align-items-center pb-3">
        <div class="img-thumbnail rounded-circle position-relative flex-shrink-0" ><img class="rounded-circle " src="{{store.logo.url}}" width="150" alt="store logo"></div>
        <div class="ps-3">
          <h3 class="text-light fs-lg mb-0">{{store.name}}</h3><span class="d-block text-light fs-ms opacity-60 py-1">Opened since {{store.create_date}}</span>
        </div>
      </div>
      <div class="d-flex">
        <div class="text-sm-end me-5">
          <div class="text-light fs-base">Total sales</div>
          <h3 class="text-light">426</h3>
        </div>
        <div class="text-sm-end">
          <div class="text-light fs-base">Store rating</div>
          <div class="star-rating"><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star"></i>
          </div>
          <div class="text-light opacity-60 fs-xs">Based on 98 reviews</div>
        </div>
      </div>
    </div>
  </div>
  <div class="container mb-5 pb-3">
    <div class="bg-light shadow-lg rounded-3 overflow-hidden">
      <div class="row">
        <!-- Sidebar-->
        <aside class="col-lg-4 pe-xl-5">
          <!-- Account menu toggler (hidden on screens larger 992px)-->
          <div class="d-block d-lg-none p-4"><a class="btn btn-outline-accent d-block" href="#store" data-bs-toggle="collapse"><i class="ci-menu me-2"></i>Account menu</a></div>
          <!-- Actual menu-->
          <div class="h-100 border-end mb-2">
            <div class="d-lg-block collapse" id="store">
              <div class="bg-secondary p-4">
                <h3 class="fs-sm mb-0 text-muted">Store Dashboard</h3>
              </div>
              <ul class="list-unstyled mb-0">
                <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 active" href="{% url 'store:store_dashboard' store.slug %}"><i class="ci-settings opacity-60 me-2"></i>Settings</a></li>
                <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:store_products' store.slug %}"><i class="ci-package opacity-60 me-2"></i>Products<span class="fs-sm text-muted ms-auto">{{products.count}}</span></a></li>
                <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:store_orders' store.slug %}"><i class="ci-package opacity-60 me-2"></i>Orders<span class="fs-sm text-muted ms-auto"></span></a></li>
                <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'store:add_product' store.slug %}"><i class="ci-cloud-upload opacity-60 me-2"></i>Add New Product</a></li>
                <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="#"><i class="ci-dollar opacity-60 me-2"></i>Sales<span class="fs-sm text-muted ms-auto">$1,375.00</span></a></li>
              </ul>
              <hr>
            </div>
          </div>
        </aside>
        
        <section  class="col-lg-8 pt-lg-4 pb-4 mb-3">
            <h1 class="title">Edit store</h1>

            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}

                <div class="field">
                    <div class="control">
                        <button class="btn btn-primary is-dark is-uppercase">Save changes</button>
                    </div>
                </div>
            </form> 

        </section>
      </div>
    </div>
  </div>

{% endblock %}

store/templates/request_category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}

<!-- Page Title-->
 <div class="page-title-overlap bg-dark pt-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
      <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
            <li class="breadcrumb-item"><a class="text-nowrap" href="{% url 'discover:home' %}"><i class="ci-home"></i>Home</a></li>
            <li class="breadcrumb-item text-nowrap"><a href="#">Account</a>
            </li>
            <li class="breadcrumb-item text-nowrap active" aria-current="page">create category request</li>
          </ol>
        </nav>
      </div>
      <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
        <h1 class="h3 text-light mb-0">Profile </h1>
      </div>
    </div>
  </div>
  <div class="container pb-5 mb-2 mb-md-4">
    <div class="row">
      <!-- Sidebar-->
      <aside class="col-lg-4 pt-4 pt-lg-0 pe-xl-5">
        <div class="bg-white rounded-3 shadow-lg pt-1 mb-5 mb-lg-0">
          <div class="d-md-flex justify-content-between align-items-center text-center text-md-start p-4">
            <div class="d-md-flex align-items-center">
              <div class="img-thumbnail rounded-circle position-relative flex-shrink-0 mx-auto mb-2 mx-md-0 mb-md-0" style="width: 6.375rem;"><img class="rounded-circle" src="{{request.user.userprofile.profile_picture.url}}" alt="user picture"></div>
              <div class="ps-md-3">
                <h3 class="fs-base mb-0">{{user.username}}</h3><span class="text-accent fs-sm">{{user.email}}</span>
              </div>
            </div><a class="btn btn-primary d-lg-none mb-2 mt-3 mt-md-0" href="#account-menu" data-bs-toggle="collapse" aria-expanded="false"><i class="ci-menu me-2"></i>Account menu</a>
          </div>
          <div class="d-lg-block collapse" id="account-menu">
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Account settings</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 " href="{% url 'dashboard:edit_profile' %}"><i class="ci-user opacity-60 me-2"></i>Profile info</a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="#"><i class="ci-location opacity-60 me-2"></i>Addresses</a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="#"><i class="ci-card opacity-60 me-2"></i>Payment methods</a></li>
              <li class="d-lg-none border-top mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:logout' %}"><i class="ci-sign-out opacity-60 me-2"></i>Sign out</a></li>
            </ul>
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Dashboard</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:stores' %}"><i class="ci-bag opacity-60 me-2"></i>Stores<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:orders' %}"><i class="ci-bag opacity-60 me-2"></i>Orders<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:wishlist' %}"><i class="ci-heart opacity-60 me-2"></i>Wishlist<span class="fs-sm text-muted ms-auto">3</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="#"><i class="ci-help opacity-60 me-2"></i>My tickets<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 active" href="{% url 'store:create_store' %}"><i class="ci-help opacity-60 me-2"></i>become vendor </a></li>
            </ul>
          </div>
        </div>
      </aside>
      <!-- Content  -->
      <section class="col-lg-8">
        <div class="bg-white rounded-3 shadow-lg pt-1 pb-2 mb-5 mb-lg-0">
        <div class="container mt-4 mb-4">
            <div class="col-md-12 ">
                <h2 class="h4 mb-3">Request category </h2>
                <p class="fs-sm text-muted mb-4"> Request adding a new category, add your products & enjoy selling them !</p>
                <form  method="POST" action="" enctype='multipart/form-data'>
                  {% csrf_token %}
                  {{form|crispy}}
                  <br>
                <button class="btn btn-primary" value="submit"><i class="ci-store me-2 ms-n21"></i>Request</button>
                </form>
            </div>
        </div>
    </div>
      </section>
    </div>
  </div>

  {% endblock %}