accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.home, name='home'),
    
    #reset_password  
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    
    #change_password
    path('change_password/', views.change_password, name='change_password'),
   ]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:blogpost>/', views.blogpost, name='blogpost'),
    path('like/<slug:blogpost>',views.like, name = 'like'),
    path('comment/<slug:blogpost>',views.add_comment, name = 'add_comment'),



]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('profile/', views.edit_profile, name='edit_profile'),

    path('addresses/', views.addresses, name='addresses'),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),


    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),

    path('stores/', views.stores, name='stores'),
    path('store/<slug:slug>/products', views.store_products, name='store_products'),
    path('store/<slug:slug>/orders', views.store_orders, name='store_orders'),
    path('store/<slug:slug>/orders/<int:order_id>', views.store_order_details, name='store_order_details'),
    path('store/<slug:slug>/orders/<int:order_id>/accept_order', views.accept_order, name='accept_order'),  
    path('store/<slug:slug>/orders/<int:order_id>/order_completed', views.order_completed, name='order_completed'),  
    path('store/<slug:slug>/orders/<int:order_id>/order_canceled', views.order_canceled, name='order_canceled'),  


    #user orders
    path('orders/', views.orders, name='orders'),
    path('orders/order/<int:order_id>', views.order_details, name ='user_order_details'),


   
]

discover/urls.py
from django.urls import path
from . import views

app_name = 'discover'

urlpatterns = [
    path('', views.home, name='home'),
    path('product/<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'), 

    path('discover/', views.discoverPage, name='discover_page'),
    path('search/', views.search, name='search'),
    path('discover/category/<slug:category_slug>/', views.category, name ='category'),
    path('category/<slug:category_slug>/', views.products_by_category, name ='products_by_category'),

]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('create_store/', views.createStore, name='create_store'),
    path('stores/store/<slug:slug>', views.store, name='store_dashboard'),
    path('stores/store/<slug:slug>/add_product', views.add_product, name='add_product'),
    path('submit_review/<slug:category_slug>/<slug:product_slug>/', views.submit_review, name='submit_review'),
    path('all_stores/', views.all_stores, name='all_stores'),
    path('edit-product/<slug:product_slug>/', views.edit_product, name='edit_product'),
    path("products/delete/<slug:product_slug>/", views.delete_product, name="delete_product"),

    path('all_stores/single_store/<slug:slug>', views.single_store, name='single_store'),
    path('store/edit-store/<slug:slug>/', views.edit_store, name='edit_store'),
    path("stores/delete/<slug:slug>/", views.delete_store, name="delete_store"),
    
]

support/urls.py
from django.urls import path
from . import views

app_name = 'support'

urlpatterns = [
    #tickets
    path('tickets/', views.tickets, name='tickets'),
    path('tickets/single_ticket/<int:ticket_id>', views.single_ticket, name='single_ticket'),
    path('tickets/single_ticket/submit', views.submit_ticket, name='submit_ticket'),

]

tufleur/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('marketplaceadmin/', include('adminshop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('discover.urls', namespace='discover')),
    path('', include('store.urls', namespace='store')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('order.urls', namespace='order')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('notifications.urls', namespace='notifications')),
    path('', include('support.urls', namespace='support')),



    path('ckeditor/', include('ckeditor_uploader.urls')),



]
 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

store/forms.py
from django.forms import ModelForm, widgets
from django import forms
from .models import Store, Product, ReviewRating


class CreateStoreForm(ModelForm):
    class Meta:
        model = Store
        fields = ['name','logo','description','trader_license', 'phone_number', 'city', 'address']
        def __init__(self, *args, **kwargs):
            super(CreateStoreForm, self).__init__(*args, **kwargs)
            self.fields['trader_license'].required = False

        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product name here..."
            }), 
            "logo": forms.ClearableFileInput(attrs={
                "class": "form-control",
            }),
             "description": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Description of the product...",
                "rows": 5
            }),
            "trader_license": forms.ClearableFileInput(attrs={
                "class": "form-control",
            }),
            "phone_number": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the store's phone number here..."
            }),
            "city": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the store's city location here..."
            }),
            "address": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the store address here..."
            }),

        }


class ProductForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
        "class": "form-control",
        "multiple": True,
    }))

    class Meta:
        model = Product
        fields = ["name","category", "image", "price","description", 'stock', "return_policy",]
        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product name here..."
            }),
            "category": forms.Select(attrs={
                "class": "form-control"
            }),
            "image": forms.ClearableFileInput(attrs={
                "class": "form-control",
            }),
            "price": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Entre price of the product..."
            }),
            "description": forms.Textarea(attrs={
                "class": "form-control",
                "placeholder": "Description of the product...",
                "rows": 5
            }),
			"stock": forms.NumberInput(attrs={
                "class": "form-control",
                "placeholder": "Enter product stock ..."
            }),
            "return_policy": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the product return policy here..."
            }),
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

dashboard/views.py
from django.shortcuts import render
from store.models import Product, Store
from django.shortcuts import render, reverse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from order.models import Order, OrderItem
from django.shortcuts import render, redirect, get_object_or_404
from accounts.forms import UserProfileForm, UserForm, UserAddressForm
from accounts.models import User, UserProfile, Address
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
# Create your views here.


@login_required(login_url='login')
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('dashboard:edit_profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=userprofile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'userprofile': userprofile,
    }
    return render(request, 'profile.html', context)

@login_required(login_url='accounts:login')
def addresses(request):
    addresses = Address.objects.filter(user=request.user)
    return render(request, "addresses.html", {"addresses":addresses})

@login_required(login_url='accounts:login')
def add_address(request):
    if request.method == "POST":
        address_form = UserAddressForm(data=request.POST)
        if address_form.is_valid():
            address_form = address_form.save(commit=False)
            address_form.user = request.user
            address_form.save()
            return HttpResponseRedirect(reverse("dashboard:addresses"))
    else:
        address_form = UserAddressForm()
    return render(request, "edit_addresses.html", {"form": address_form})

@login_required(login_url='accounts:login')
def edit_address(request, id):
    if request.method == "POST":
        address = Address.objects.get(pk=id, user=request.user)
        address_form = UserAddressForm(instance=address, data=request.POST)
        if address_form.is_valid():
            address_form.save()
            return HttpResponseRedirect(reverse("dashboard:addresses"))
    else:
        address = Address.objects.get(pk=id, user=request.user)
        address_form = UserAddressForm(instance=address)
    return render(request, "edit_addresses.html", {"form": address_form})


@login_required(login_url='accounts:login')
def delete_address(request, id):
    address = Address.objects.filter(pk=id, user=request.user).delete()
    return redirect("dashboard:addresses")

@login_required(login_url='accounts:login')
def set_default(request, id):
    Address.objects.filter(user=request.user, default=True).update(default=False)
    Address.objects.filter(pk=id, user=request.user).update(default=True)

    previous_url = request.META.get("HTTP_REFERER")

    if "delivery_address" in previous_url:
        return redirect("order:delivery_address")

    return redirect("dashboard:addresses")


@login_required(login_url='accounts:login')
def wishlist(request):
    products = Product.objects.filter(users_wishlist=request.user)
    return render(request, "user_wishlist.html", {"wishlist": products})

@login_required(login_url='accounts:login')
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, id=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user)
        messages.success(request, product.name + " has been removed from your WishList")
    else:
        product.users_wishlist.add(request.user)
        messages.success(request, "Added " + product.name + " to your WishList")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])




#Get all stores by user
@login_required(login_url='accounts:login')
def stores(request):
    stores =  request.user.store_set.all()
    return render(request, 'stores.html', {'stores': stores})

@login_required(login_url='accounts:login')
def store_products(request, slug):
    user = request.user
    store = Store.objects.get(owner=user, slug=slug)

    products = Product.objects.filter(store=store)
    context = {
        'store': store,
        'products' : products
    }
    return render(request, 'store_products.html', context)


@login_required(login_url='accounts:login')
def store_orders(request, slug):
    user = request.user
    store = Store.objects.get(owner=user, slug=slug)
    orders = store.orders.all()

    for order in orders:
        order.store_amount = 0
        order.store_paid_amount = 0
        order.fully_paid = True

        for item in order.items.all():
            if item.store == store:
                if item.store_paid:
                    order.store_paid_amount += item.get_total_price()
                else:
                    order.store_amount += item.get_total_price()
                    order.fully_paid = False

    return render(request, 'store_orders.html', {'store': store, 'orders':orders })


@login_required(login_url='accounts:login')
def orders(request):
    user = request.user
    orders = user.order_set.all().order_by("-id")
    
    paginator = Paginator(orders,2)
    page = request.GET.get('page')
    paged_orders = paginator.get_page(page)
    return render(request, 'user_orders.html', {'orders': paged_orders})

@login_required(login_url='accounts:login')
def order_details(request, order_id):
    order =get_object_or_404(Order, pk=order_id)
    context = {
        'order' : order
    }
    return render(request, 'user_order_details.html', context)

@login_required(login_url='accounts:login')
def store_order_details(request,slug, order_id):
    user = request.user
    store = Store.objects.get(owner=user, slug=slug)
    order =get_object_or_404(Order, pk=order_id)
    
    order.store_amount = 0
    order.store_paid_amount = 0
    order.fully_paid = True

    for item in order.items.all():
        if item.store == store:
            if item.store_paid:
                order.store_paid_amount += item.get_total_price()
            else:
                order.store_amount += item.get_total_price()
                order.fully_paid = False
    
    context = {
       'order' : order,
        'store': store,
    }
    return render(request, 'store_order_details.html', context)


def accept_order(request,slug, order_id):
    user = request.user
    store = Store.objects.get(owner=user, slug=slug)
    order =get_object_or_404(Order, pk=order_id)

    order.status = 'Accepted'
    order.save()

    return redirect('dashboard:store_orders', store.slug)


def order_completed(request,slug, order_id):
    user = request.user
    store = Store.objects.get(owner=user, slug=slug)
    order =get_object_or_404(Order, pk=order_id)

    order.status = 'Completed'

    for item in order.items.all():
        item.ordered = True
        item.store_paid= True
        item.product.stock -= item.quantity
        item.save()
     

    order.fully_paid = True

            
    order.save()

    return redirect('dashboard:store_orders', store.slug)


def order_canceled(request,slug, order_id):
    user = request.user
    store = Store.objects.get(owner=user, slug=slug)
    order =get_object_or_404(Order, pk=order_id)

    order.status = 'Canceled'
    order.save()

    return redirect('dashboard:store_orders', store.slug)

dashboard/templates/addresses.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}

<!-- Page Title-->
 <div class="page-title-overlap bg-dark pt-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
      <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
            <li class="breadcrumb-item"><a class="text-nowrap" href="{% url 'discover:home' %}"><i class="ci-home"></i>Home</a></li>
            <li class="breadcrumb-item text-nowrap"><a href="#">Account</a>
            </li>
            <li class="breadcrumb-item text-nowrap active" aria-current="page">Profile info</li>
          </ol>
        </nav>
      </div>
      <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
        <h1 class="h3 text-light mb-0">Profile info</h1>
      </div>
    </div>
  </div>
  <div class="container pb-5 mb-2 mb-md-4">
    <div class="row">
      <!-- Sidebar-->
      <aside class="col-lg-4 pt-4 pt-lg-0 pe-xl-5">
        <div class="bg-white rounded-3 shadow-lg pt-1 mb-5 mb-lg-0">
          <div class="d-md-flex justify-content-between align-items-center text-center text-md-start p-4">
            <div class="d-md-flex align-items-center">
              <div class="img-thumbnail rounded-circle position-relative flex-shrink-0 mx-auto mb-2 mx-md-0 mb-md-0" style="width: 6.375rem;"><img class="rounded-circle" src="{{request.user.userprofile.profile_picture.url}}" alt="user picture"></div>
              <div class="ps-md-3">
                <h3 class="fs-base mb-0">{{user.username}}</h3><span class="text-accent fs-sm">{{user.email}}</span>
              </div>
            </div><a class="btn btn-primary d-lg-none mb-2 mt-3 mt-md-0" href="#account-menu" data-bs-toggle="collapse" aria-expanded="false"><i class="ci-menu me-2"></i>Account menu</a>
          </div>
          <div class="d-lg-block collapse" id="account-menu">
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Account settings</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 " href="{% url 'dashboard:edit_profile' %}"><i class="ci-user opacity-60 me-2"></i>Profile info</a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 active " href="{% url 'dashboard:addresses' %}"><i class="ci-location opacity-60 me-2"></i>Addresses</a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:change_password' %}"><i class="ci-card opacity-60 me-2"></i>Change password</a></li>
              <li class="d-lg-none border-top mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:logout' %}"><i class="ci-sign-out opacity-60 me-2"></i>Sign out</a></li>
            </ul>
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Dashboard</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:stores' %}"><i class="ci-bag opacity-60 me-2"></i>Stores<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:orders' %}"><i class="ci-bag opacity-60 me-2"></i>Orders<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:wishlist' %}"><i class="ci-heart opacity-60 me-2"></i>Wishlist<span class="fs-sm text-muted ms-auto">3</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'support:tickets' %}"><i class="ci-help opacity-60 me-2"></i>My tickets<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'store:create_store' %}"><i class="ci-help opacity-60 me-2"></i>become vendor </a></li>
            </ul>
          </div>
        </div>
      </aside>
      <!-- Content  -->
      <section class="col-lg-8">
        <!-- Toolbar-->
        <div class="d-none d-lg-flex justify-content-between align-items-center pt-lg-3 pb-4 pb-lg-5 mb-lg-3">
          <h6 class="fs-base text-light mb-0">Addresses:</h6><a class="btn btn-primary btn-sm" href="{% url 'accounts:logout' %}"><i class="ci-sign-out me-2"></i>Sign out</a>
        </div>
        <!-- Profile form-->
        {% if addresses %}
          {% for address in addresses %}
            <div class="col">
              <div class="card pb-3">
                <div class="card-header bg-white small text-muted">
                  {% if address.default %}
                    <strong> This is your Default Shipping & Billing Address</strong>
                  {% endif %}
                  &nbsp;
                </div>
                <div class="card-body small pb-1">
                  <p class="card-text m-0 fw-bold">Full Name : {{user.first_name}} {{user.last_name}}</p>
                  <p class="card-text m-0">address :{{address.address_line1}}</p>
                  <p class="card-text m-0">{{address.address_line2}}</p>
                  <p class="card-text m-0">city :{{address.city}}</p>
                  <p class="card-text m-0">country :{{address.country}}</p>
                  <p class="card-text m-0">zipcode : {{address.zipcode}}</p>
                <a href="{% url 'dashboard:edit_address' address.id %}" class="text-decoration-none">Edit &nbsp;</a> &nbsp;
                <a href="{% url 'dashboard:delete_address' address.id %}" class="text-decoration-none"> - Delete &nbsp;</a> &nbsp;
                {% if not address.default %}
                    <a href="{% url 'dashboard:set_default' address.id %}" class="text-decoration-none"> - Set Default</a>
                {% endif %}
                </div>
              </div>

            </div>
            <br>
            <br>

            {% endfor %}
            <a href="{% url 'dashboard:add_address' %}"><button class="btn btn-primary w-100"> Add new Address</button></a>

            {% else %}
            <div>you dont have any address yet, please add yours </div>
            <br>
            <a href="{% url 'dashboard:add_address' %}"><button class="btn btn-primary w-100"> Add Address</button></a>
            {%endif%}
      </section>
    </div>
  </div>

  {% endblock %}

dashboard/templates/edit_addresses.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}

<!-- Page Title-->
 <div class="page-title-overlap bg-dark pt-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
      <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
            <li class="breadcrumb-item"><a class="text-nowrap" href="{% url 'discover:home' %}"><i class="ci-home"></i>Home</a></li>
            <li class="breadcrumb-item text-nowrap"><a href="#">Account</a>
            </li>
            <li class="breadcrumb-item text-nowrap active" aria-current="page">Profile info</li>
          </ol>
        </nav>
      </div>
      <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
        <h1 class="h3 text-light mb-0">Profile info</h1>
      </div>
    </div>
  </div>
  <div class="container pb-5 mb-2 mb-md-4">
    <div class="row">
      <!-- Sidebar-->
      <aside class="col-lg-4 pt-4 pt-lg-0 pe-xl-5">
        <div class="bg-white rounded-3 shadow-lg pt-1 mb-5 mb-lg-0">
          <div class="d-md-flex justify-content-between align-items-center text-center text-md-start p-4">
            <div class="d-md-flex align-items-center">
              <div class="img-thumbnail rounded-circle position-relative flex-shrink-0 mx-auto mb-2 mx-md-0 mb-md-0" style="width: 6.375rem;"><img class="rounded-circle" src="{{request.user.userprofile.profile_picture.url}}" alt="user picture"></div>
              <div class="ps-md-3">
                <h3 class="fs-base mb-0">{{user.username}}</h3><span class="text-accent fs-sm">{{user.email}}</span>
              </div>
            </div><a class="btn btn-primary d-lg-none mb-2 mt-3 mt-md-0" href="#account-menu" data-bs-toggle="collapse" aria-expanded="false"><i class="ci-menu me-2"></i>Account menu</a>
          </div>
          <div class="d-lg-block collapse" id="account-menu">
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Account settings</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3 active" href="{% url 'dashboard:edit_profile' %}"><i class="ci-user opacity-60 me-2"></i>Profile info</a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:addresses' %}"><i class="ci-location opacity-60 me-2"></i>Addresses</a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:change_password' %}"><i class="ci-card opacity-60 me-2"></i>Change password</a></li>
              <li class="d-lg-none border-top mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'accounts:logout' %}"><i class="ci-sign-out opacity-60 me-2"></i>Sign out</a></li>
            </ul>
            <div class="bg-secondary px-4 py-3">
              <h3 class="fs-sm mb-0 text-muted">Dashboard</h3>
            </div>
            <ul class="list-unstyled mb-0">
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:stores' %}"><i class="ci-bag opacity-60 me-2"></i>Stores<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:orders' %}"><i class="ci-bag opacity-60 me-2"></i>Orders<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'dashboard:wishlist' %}"><i class="ci-heart opacity-60 me-2"></i>Wishlist<span class="fs-sm text-muted ms-auto">3</span></a></li>
              <li class="border-bottom mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'support:tickets' %}"><i class="ci-help opacity-60 me-2"></i>My tickets<span class="fs-sm text-muted ms-auto">1</span></a></li>
              <li class="mb-0"><a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'store:create_store' %}"><i class="ci-help opacity-60 me-2"></i>become vendor </a></li>
            </ul>
          </div>
        </div>
      </aside>
      <!-- Content  -->
      <section class="col-lg-8">
        <!-- Toolbar-->
        <div class="d-none d-lg-flex justify-content-between align-items-center pt-lg-3 pb-4 pb-lg-5 mb-lg-3">
          <h6 class="fs-base text-light mb-0">Add / Edit Address</h6><a class="btn btn-primary btn-sm" href="{% url 'accounts:logout' %}"><i class="ci-sign-out me-2"></i>Sign out</a>
        </div>

          <div class="col-12 mx-auto">
          
         
          <form name="address_form" class="account-form" method="post" enctype="multipart/form-data">
            {% if form.errors %}
            <div class="alert alert-primary" role="alert">
              Error: Please try again!
            </div>
            {% endif %}
            {% csrf_token %}
            <label class="small fw-bold">{{ form.address_line1.label}}</label>
            {{ form.address_line1 }}
            <label class="small fw-bold">{{ form.address_line2.label}}</label>
            {{ form.address_line2 }}
            <label class="small fw-bold">{{ form.city.label}}</label>
            {{ form.city }}
            <label class="small fw-bold">{{ form.country.label}}</label>
            {{ form.country }}
            <label class="small fw-bold">{{ form.zipcode.label}}</label>
            {{ form.zipcode }}
            <button class="btn btn-primary btn-block py-2 mb-4 mt-4 fw-bold w-100" type="button" value="Submit" onclick="submitForm()">
            Add / Edit Address
            </button>
          </form>

        </div>
      </section>
    </div>
  </div>



<script>
    function submitForm() {
       var form = document.getElementsByName('address_form')[0];
       form.submit(); // Submit the form
       form.reset();  // Reset all form data
       return false; // Prevent page refresh
    }
</script>

  {% endblock %}